spring:
  session:
    store-type: redis
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.81.133:3306/gulimall_pms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.81.133
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
#      key-prefix: CACHE_
      # 防止缓存穿透
      cache-null-values: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 11000
logging:
  level:
    com.zyj.gulimall: debug
gulimall:
  thread:
    core-size: 10
    max-size: 20
    keep-alive-time: 20
