spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.81.133
    port: 6379
  session:
    store-type: redis
server:
  port: 13000
