spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: 
        bucket: 
      sms:
        host: 
        path: 
        appcode: 
  application:
    name: gulimall-third-party
server:
  port: 30000
